name: Simple semver release

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Database Version
        id: db-version
        uses: paulhatch/semantic-version@v5.0.2
        with:
          change_path: "."
          namespace: ""
